### ISSUE TITLE
谨慎啊。。。。

### ISSUE THREAD

**Issue by fccwhatt** [PUGE/crawler#2]
顺便也看了你的代码还不错啊，逻辑很清晰。还绕过了他们的设备限制和请求签名。
不过你现在这样大量扩散用户相关信息，即便是爬取来的，还真没人敢这么做。既然微云给你封了，你应该明白。还上传。。。。年轻人，谨慎啊 。相关的项目赶紧干掉吧 。

**Comment by PUGE** [comment]
嘿嘿 谢谢夸奖 这个代码已经比较久了，他们的系统应该已经进行了升级 而且配置文件并没有公布 所以不是很专业无法使用 不过我会注意的 稍后删除这个工程
